-- M2B: Roster Management — shift rotations + delegation + overrides relation
--
-- Adds the M2B roster primitives (PRD FR-M2B-002..004, FR-M0-060/061):
--   * shift_definitions — configurable shift windows (NORMAL/PAGI/SIANG/MALAM)
--     with a `crosses_midnight` flag so a night shift belongs to the Indonesian
--     day it STARTS on (attendance work_date = UTC-midnight convention).
--   * shift_patterns + shift_rotations — named rotation cycles for SHIFT
--     work_schedules (per-date resolution = position in the cycle).
--   * work_schedules.shift_pattern_id — SHIFT schedules point at a pattern.
--   * schedule_overrides.employee relation — per-date roster override rows.
--   * approval_delegations relations — delegator/delegate user FKs.
--
-- Generated by hand to match the init migration conventions; applied with
-- `prisma migrate deploy` (non-interactive).

-- 1. shift_definitions
CREATE TABLE "shift_definitions" (
    "id" UUID NOT NULL,
    "company_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "start_time" TEXT,
    "end_time" TEXT,
    "break_minutes" INTEGER NOT NULL DEFAULT 60,
    "late_tolerance_minutes" INTEGER NOT NULL DEFAULT 0,
    "crosses_midnight" BOOLEAN NOT NULL DEFAULT false,
    "cover_end_date" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "shift_definitions_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "shift_definitions_company_id_code_key" ON "shift_definitions"("company_id", "code");
CREATE INDEX "shift_definitions_company_id_idx" ON "shift_definitions"("company_id");

-- 2. shift_patterns
CREATE TABLE "shift_patterns" (
    "id" UUID NOT NULL,
    "company_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "cycle_length" INTEGER NOT NULL DEFAULT 7,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "shift_patterns_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "shift_patterns_company_id_code_key" ON "shift_patterns"("company_id", "code");
CREATE INDEX "shift_patterns_company_id_idx" ON "shift_patterns"("company_id");

-- 3. shift_rotations
CREATE TABLE "shift_rotations" (
    "id" UUID NOT NULL,
    "shift_pattern_id" UUID NOT NULL,
    "day_index" INTEGER NOT NULL,
    "shift_definition_id" UUID,
    "is_working_day" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "shift_rotations_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "shift_rotations_shift_pattern_id_day_index_key" ON "shift_rotations"("shift_pattern_id", "day_index");
CREATE INDEX "shift_rotations_shift_definition_id_idx" ON "shift_rotations"("shift_definition_id");

-- 4. work_schedules.shift_pattern_id
ALTER TABLE "work_schedules" ADD COLUMN "shift_pattern_id" UUID;
CREATE INDEX "work_schedules_shift_pattern_id_idx" ON "work_schedules"("shift_pattern_id");

-- 5. Foreign keys
ALTER TABLE "shift_definitions" ADD CONSTRAINT "shift_definitions_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "shift_patterns" ADD CONSTRAINT "shift_patterns_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "shift_rotations" ADD CONSTRAINT "shift_rotations_shift_pattern_id_fkey" FOREIGN KEY ("shift_pattern_id") REFERENCES "shift_patterns"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "shift_rotations" ADD CONSTRAINT "shift_rotations_shift_definition_id_fkey" FOREIGN KEY ("shift_definition_id") REFERENCES "shift_definitions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "work_schedules" ADD CONSTRAINT "work_schedules_shift_pattern_id_fkey" FOREIGN KEY ("shift_pattern_id") REFERENCES "shift_patterns"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- 6. schedule_overrides → employees (roster override rows)
ALTER TABLE "schedule_overrides" ADD CONSTRAINT "schedule_overrides_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- 7. approval_delegations → users (delegation feature, FR-M0-060/061)
ALTER TABLE "approval_delegations" ADD CONSTRAINT "approval_delegations_delegator_user_id_fkey" FOREIGN KEY ("delegator_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "approval_delegations" ADD CONSTRAINT "approval_delegations_delegate_user_id_fkey" FOREIGN KEY ("delegate_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "approval_delegations_delegate_user_id_is_active_idx" ON "approval_delegations"("delegate_user_id", "is_active");
CREATE INDEX "approval_delegations_delegator_user_id_idx" ON "approval_delegations"("delegator_user_id");