-- M2: HR operational modules — grill decisions (ADR-0001..0003 + CONTEXT.md)
-- Generated by hand to match the init migration conventions; applied with
-- `prisma migrate deploy` (non-interactive). Next `migrate dev` will mark it applied.

-- @@unique([trip_request_id, top_up_sequence]) on cash_advances
-- Cascade: the composite unique is SAFER than the standalone index (a unique
-- constraint already creates an index), so the standalone index is dropped.
-- Unique constraints are created by Prisma as separate objects, so we drop
-- both the standalone index on top_up_sequence and the composite unique.

-- 1. trip_requests: ADR-0001 classification inputs
ALTER TABLE "trip_requests" ADD COLUMN "distance_km" DECIMAL(10,2);
ALTER TABLE "trip_requests" ADD COLUMN "is_overnight" BOOLEAN NOT NULL DEFAULT false;

-- 2. trip_expense_lines: ADR-0002 per-line funding source
ALTER TABLE "trip_expense_lines" ADD COLUMN "funding_source" TEXT NOT NULL DEFAULT 'ADVANCE';

-- 3. cash_advances: ADR-0002 sequenced child advances (top-up support)
ALTER TABLE "cash_advances" ADD COLUMN "doc_number" TEXT;
ALTER TABLE "cash_advances" ADD COLUMN "top_up_sequence" INTEGER NOT NULL DEFAULT 1;
CREATE UNIQUE INDEX "cash_advances_doc_number_key" ON "cash_advances"("doc_number");
CREATE UNIQUE INDEX "cash_advances_trip_request_id_top_up_sequence_key" ON "cash_advances"("trip_request_id", "top_up_sequence");

-- 4. schedule_overrides: ADR-0003 ganti hari = paired bidirectional swap
ALTER TABLE "schedule_overrides" ADD COLUMN "swap_pair_id" UUID;
ALTER TABLE "schedule_overrides" ADD COLUMN "approval_instance_id" UUID;

-- 5. loan_types: pinjaman purpose whitelist (CONTEXT.md)
ALTER TABLE "loan_types" ADD COLUMN "allowed_purposes" JSONB;

-- 6. license_financings: SIM 50:50 payroll clawback recovery
CREATE TABLE "license_financing_installments" (
    "id" UUID NOT NULL,
    "license_financing_id" UUID NOT NULL,
    "payroll_period_id" UUID NOT NULL,
    "sequence_no" INTEGER NOT NULL,
    "amount" DECIMAL(18,2) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "paid_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "license_financing_installments_pkey" PRIMARY KEY ("id")
);

-- 7. BRD 6.4: partial index on attendance_logs.mock-location rows
CREATE INDEX "attendance_logs_is_mock_location_idx" ON "attendance_logs"("is_mock_location")
    WHERE "is_mock_location" = TRUE;

-- 8. Foreign keys for the new installments table (matches loan_installments style)
ALTER TABLE "license_financing_installments" ADD CONSTRAINT "license_financing_installments_license_financing_id_fkey"
    FOREIGN KEY ("license_financing_id") REFERENCES "license_financings"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "license_financing_installments" ADD CONSTRAINT "license_financing_installments_payroll_period_id_fkey"
    FOREIGN KEY ("payroll_period_id") REFERENCES "payroll_periods"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Indexes to match Prisma's generated shape for the new table
CREATE UNIQUE INDEX "license_financing_installments_license_financing_id_sequence_no_key"
    ON "license_financing_installments"("license_financing_id", "sequence_no");

-- 9. Fix attendance_allowance_rules exclusion: the ladder needs multiple
--    brackets per rule_set_code (1 absence → 50%, 2 → 0), so the period
--    anti-overlap must also key on absence_days_min. The init constraint was
--    keyed on (rule_set_code, tsrange) only, which cannot hold sibling brackets.
ALTER TABLE "attendance_allowance_rules" DROP CONSTRAINT "attendance_allowance_rules_no_overlap";
ALTER TABLE "attendance_allowance_rules"
    ADD CONSTRAINT "attendance_allowance_rules_no_overlap"
    EXCLUDE USING gist (
        "rule_set_code" WITH =,
        "absence_days_min" WITH =,
        tsrange("effective_from", COALESCE("effective_to", 'infinity'::timestamp), '[)') WITH &&
    );